name: Deploy main to production enviroment
run-name: ${{ github.actor }} is deploying to production

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying to production"
      - uses: actions/checkout@v2

      - name: Deploy to production
        if: github.event.pull_request.merged == true
        run: |
          echo "Deploying to production"

      - name: Deploy to sandbox server
        uses: fifsky/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_SERVER_IP }}
          user: ${{ secrets.DEPLOY_SERVER_USER }}
          key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
          port: ${{ secrets.DEPLOY_SERVER_PORT }}
          command: |
            cd ocwsb/
            git checkout main
            rm yarn.lock
            git pull
            yarn install
            yarn build
            pm2 reload all
            npx prisma generate
